name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push linux
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.linux
          push: true
          tags: codablock/pyinstaller-images:latest-linux
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push wine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.wine
          push: true
          tags: codablock/pyinstaller-images:latest-wine
          cache-from: type=gha
          cache-to: type=gha,mode=max
